spring:
  profiles:
   active:
   - dev
---
content: dev content 刷新出来看看1111111111
spring:
  profiles: dev
  application:
    name: hello-service
---
content: test content
spring:
  profiles: test
  application:
    name: hello-service
